### PR TITLE
Allow subclassing of AnimatedCollectionViewLayout

### PR DESCRIPTION
**Pull request by Voxar**

### CODE REVIEW

**Comment by KelvinJin** [comment]
Hey, thanks for the PR. However, I'm not sure allowing people to subclass the layout would help much. If there're features that you need to subclass to achieve, then maybe add them to the base class?

**Comment by Voxar** [comment]
Hi. Thanks for your comment. 

I'm just interested in `func targetContentOffset(forProposedContentOffset proposedContentOffset: CGPoint, withScrollingVelocity velocity: CGPoint) -> CGPoint` really, to make a custom pagination to get "flick fast scroll" functionality. Works pretty good together with `LinearCardAttributesAnimator`.

Which approach would you suggest?

**Comment by KelvinJin** [comment]
Hey Voxar. That sounds like a very interesting feature to have in this library. Do you think we can add that as a plugin/optional feature that if you want you can turn it on?

**Comment by kamendo** [comment]
Please merge, I need this one

**Comment by gsbernstein** [comment]
Please merge this, I just made a similar PR with just the class opened. This is necessary to use other features of UICollectionViewFlowLayout like finalLayoutAttributesForDisappearingItem and initialLayoutAttributesForAppearingItem to customize the appearing and dismissing of cells.

**Comment by KelvinJin** [comment]
@kamendo  @gsbernstein Thanks guys and good point. I'll merge this and release a new version as soon as I get home today (in about 8 hours).

**Comment by gsbernstein** [comment]
Thank you! Impressed by your responsiveness.

**Comment by kamendo** [comment]
Works great! 10q!

**Pull request merged**
